import { library } from "@fortawesome/fontawesome-svg-core";
import {
	faCircleNotch,
	faArrowLeft,
	faSpinner,
	faSlidersH,
	faChevronRight,
	faSearch,
	faPlayCircle,
	faBook,
	faTimes,
	faCheck,
	faBan,
	faTimesCircle,
	faPlay,
	faPause,
	faVolumeDown,
	faVolumeMute,
	faVolumeOff,
	faVolumeUp,
	faExpand,
	faCompress,
	faCog,
} from "@fortawesome/free-solid-svg-icons";
import { faClock, faCheckCircle } from "@fortawesome/free-regular-svg-icons";

library.add(
	faCircleNotch,
	faArrowLeft,
	faSpinner,
	faChevronRight,
	faSlidersH,
	faCog,
	faSearch,
	faCheck,
	faBook,
	faTimes,
	faPlayCircle,
	faBan,
	faPlay,
	faPause,
	faTimesCircle,
	faClock,
	faCheckCircle,
	faVolumeDown,
	faVolumeMute,
	faVolumeOff,
	faVolumeUp,
	faExpand,
	faCompress
);
